// Code generated by protoc-gen-go. DO NOT EDIT.
// source: function.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Function struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Root                 string            `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Running              bool              `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Pid                  uint32            `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Network              *Function_Network `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{0}
}

func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (m *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(m, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Function) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *Function) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *Function) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Function) GetNetwork() *Function_Network {
	if m != nil {
		return m.Network
	}
	return nil
}

type Function_Network struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Gateway              string   `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Mask                 string   `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Function_Network) Reset()         { *m = Function_Network{} }
func (m *Function_Network) String() string { return proto.CompactTextString(m) }
func (*Function_Network) ProtoMessage()    {}
func (*Function_Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{0, 0}
}

func (m *Function_Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function_Network.Unmarshal(m, b)
}
func (m *Function_Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function_Network.Marshal(b, m, deterministic)
}
func (m *Function_Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function_Network.Merge(m, src)
}
func (m *Function_Network) XXX_Size() int {
	return xxx_messageInfo_Function_Network.Size(m)
}
func (m *Function_Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Function_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Function_Network proto.InternalMessageInfo

func (m *Function_Network) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Function_Network) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *Function_Network) GetMask() string {
	if m != nil {
		return m.Mask
	}
	return ""
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateResponse struct {
	Function             *Function `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Functions            []*Function `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

func init() {
	proto.RegisterType((*Function)(nil), "protocol.Function")
	proto.RegisterType((*Function_Network)(nil), "protocol.Function.Network")
	proto.RegisterType((*CreateRequest)(nil), "protocol.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "protocol.CreateResponse")
	proto.RegisterType((*ListRequest)(nil), "protocol.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "protocol.ListResponse")
}

func init() { proto.RegisterFile("function.proto", fileDescriptor_8ac74addf543d91a) }

var fileDescriptor_8ac74addf543d91a = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xb6, 0x6a, 0xd3, 0x2b, 0x2d, 0xe8, 0x24, 0xc0, 0xca, 0x14, 0x85, 0x25, 0x53,
	0x84, 0x0a, 0x4c, 0x2c, 0x95, 0x90, 0x60, 0x41, 0x0c, 0xe6, 0x09, 0x42, 0x31, 0x95, 0x55, 0x6a,
	0x07, 0xdb, 0xa1, 0xe2, 0x01, 0x78, 0x4c, 0xde, 0x05, 0xd9, 0xb1, 0x09, 0x50, 0x98, 0x72, 0xf7,
	0xfb, 0xb3, 0xef, 0xbb, 0xc0, 0xec, 0xa9, 0x91, 0x4b, 0x2b, 0x94, 0x2c, 0x6b, 0xad, 0xac, 0xc2,
	0xc4, 0x7f, 0x96, 0xea, 0x39, 0xff, 0x20, 0x90, 0x5c, 0x87, 0x43, 0x44, 0x18, 0xc8, 0x6a, 0xc3,
	0x29, 0xc9, 0x48, 0x31, 0x66, 0xbe, 0x76, 0x99, 0x56, 0xca, 0xd2, 0x5e, 0x9b, 0xb9, 0x1a, 0x29,
	0x8c, 0x74, 0x23, 0xa5, 0x90, 0x2b, 0xda, 0xcf, 0x48, 0x91, 0xb0, 0xd8, 0xe2, 0x01, 0xf4, 0x6b,
	0xf1, 0x48, 0x07, 0x19, 0x29, 0xa6, 0xcc, 0x95, 0x78, 0x0e, 0x23, 0xc9, 0xed, 0x56, 0xe9, 0x35,
	0x1d, 0x66, 0xa4, 0x98, 0xcc, 0xd3, 0x32, 0x0e, 0x2f, 0xe3, 0xe0, 0xf2, 0xae, 0x25, 0x58, 0x44,
	0xd3, 0x1b, 0x18, 0x85, 0x0c, 0x67, 0xd0, 0x13, 0x75, 0x50, 0xea, 0x89, 0xda, 0x0d, 0x5f, 0x55,
	0x96, 0x6f, 0xab, 0xb7, 0xe0, 0x14, 0x5b, 0xa7, 0xba, 0xa9, 0xcc, 0xda, 0x3b, 0x8d, 0x99, 0xaf,
	0xf3, 0x13, 0x98, 0x5e, 0x69, 0x5e, 0x59, 0xce, 0xf8, 0x4b, 0xc3, 0x8d, 0xfd, 0x6b, 0xc7, 0x7c,
	0x01, 0xb3, 0x08, 0x99, 0x5a, 0x49, 0xc3, 0xb1, 0x84, 0x24, 0xfe, 0x32, 0x4f, 0x4e, 0xe6, 0xb8,
	0xab, 0xcd, 0xbe, 0x98, 0x7c, 0x0a, 0x93, 0x5b, 0x61, 0x6c, 0x18, 0x92, 0x2f, 0x60, 0xaf, 0x6d,
	0xc3, 0x73, 0xa7, 0x30, 0x8e, 0xa8, 0xa1, 0x24, 0xeb, 0xff, 0xf3, 0x5e, 0x07, 0xcd, 0xdf, 0x09,
	0xec, 0xc7, 0xfc, 0x9e, 0xeb, 0x57, 0xb1, 0xe4, 0x78, 0x09, 0xc3, 0x56, 0x13, 0x8f, 0xbb, 0xcb,
	0x3f, 0xb6, 0x4b, 0xe9, 0xee, 0x41, 0x50, 0xb8, 0x80, 0x81, 0x53, 0xc2, 0xc3, 0x8e, 0xf8, 0x66,
	0x9c, 0x1e, 0xfd, 0x8e, 0xdb, 0x6b, 0x0f, 0x43, 0x1f, 0x9f, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x70, 0xcc, 0x13, 0x1e, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FunctionServiceClient is the client API for FunctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type functionServiceClient struct {
	cc *grpc.ClientConn
}

func NewFunctionServiceClient(cc *grpc.ClientConn) FunctionServiceClient {
	return &functionServiceClient{cc}
}

func (c *functionServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/protocol.FunctionService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/protocol.FunctionService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServiceServer is the server API for FunctionService service.
type FunctionServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterFunctionServiceServer(s *grpc.Server, srv FunctionServiceServer) {
	s.RegisterService(&_FunctionService_serviceDesc, srv)
}

func _FunctionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.FunctionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.FunctionService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FunctionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.FunctionService",
	HandlerType: (*FunctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _FunctionService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FunctionService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "function.proto",
}
